FEAT: Added productlisting-filters
kotesh-arya/E-commerce-react pull request #8
Opened 2022-06-03 12:20 UTC by kotesh-arya

## Added the following filters for ProductListing Page
- Rating filter 
- Men, Women, Stock, Delivery type filters.
- Price sorting

2022-06-03 13:27 UTC, swethaogeti commented on src/pages/ProductList/ProductlistCard.jsx
> +            .map((_, index) => (
nice trick !!

2022-06-03 13:28 UTC, swethaogeti commented on src/pages/ProductList/filters/filters.jsx
> +                  // console.log("decrease");
remove comments

2022-06-03 13:31 UTC, swethaogeti approved these changes
everything looks clean . Be consistent with z-index and margin . Rest is fine. GTM

2022-06-03 14:47 UTC, MaruthiPothuganti requested changes
A bug while toggling the women category filter in Product listing Page. Except that everything else looks good

![image](https://user-images.githubusercontent.com/67600170/171877680-a8eb3ea7-0788-421e-b5dc-9f0cfcae640e.png)

![image](https://user-images.githubusercontent.com/67600170/171877701-1923a450-8564-44d2-85db-e1f737edfe75.png)

2022-06-04 02:32 UTC, kotesh-arya commented on src/pages/ProductList/ProductlistCard.jsx
> +            .map((_, index) => (
Thank you!!!

2022-06-04 02:34 UTC, kotesh-arya commented on src/pages/ProductList/filters/filters.jsx
> +                  // console.log("decrease");
Sure 👍🏻

2022-06-04 04:24 UTC, kotesh-arya commented
> Fixed it and Thanks for pointing out 👍🏻 

>![Screenshot (36)](https://user-images.githubusercontent.com/69259490/171982609-9e505b1a-0d65-4185-bc99-7454b3c0dd9a.png)

2022-06-04 07:46 UTC, merged